FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

COPY AImage-Gen-service/image-generator/ /app/

EXPOSE 5001

CMD ["python", "app.py"]
