FROM node:18-alpine as build

WORKDIR /app
COPY app-ai-ro-frontend/package*.json ./
RUN npm install
COPY app-ai-ro-frontend/ .
RUN npm run build

FROM nginx:stable-alpine

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
