

services:
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-ai-ro-backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      - FLASK_ENV=development
      - RQ_REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis

  rq_worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-ai-ro-rq-worker
    restart: always
    command: rq worker default
    environment:
      - RQ_REDIS_URL=redis://redis:6379/0
      - FLASK_ENV=development
    depends_on:
      - redis
      - backend
